services:
  database:
    image: postgres
    container_name: DivideAe_DB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=divideAe_db
    volumes:
      - pgdata:/data/postgres
  redis:
    image: redis
    container_name: DivideAe_Redis
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
