packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8
  nativewind: ~4.0.36
  tailwindcss: ^3.4.10

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
